import React, { useState, useEffect,useContext } from "react";
import Head from "next/head";
import Image from "next/image";
import classNames from "classnames";
import styles from "../styles/Home.module.css";
import MemberCard from "../components/MemberCard";
import OpportunityCard from "../components/OpportunityCard";
import RequestCard from "../components/RequestCard";
import ItemsCarousel from "react-items-carousel";
import SelectInput from "../components/SelectInput";
import TextInput from "../components/TextInput";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faMagnifyingGlass, faChev } from "@fortawesome/free-solid-svg-icons";
import Footer from "../components/Footer";
import AuthenticationContext from "../context/AuthenticationContext";

export default function Home({ done }) {
    const members = [];
  const [userInfo,setUserInfo]=useState({})
  const [activeItemIndex, setActiveItemIndex] = useState(0);
  const chevronWidth = 40;
  const [show, setShow] = useState("questionOne");
  const { user, accessToken } = useContext(AuthenticationContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.slider}>
            <div className={styles.search_box}>
              <h1 className="main_title">Get connected to the best Mentors</h1>
              <h2>
                Book and meet mentors and mentees from all around sudan for 1:1
                mentorship in our community
              </h2>
              <div className={styles.search}>
                <div className={styles.search_fields_box}>
                  <SelectInput />
                </div>
                <div className={styles.search_text}>
                  <TextInput
                    type="text"
                    placeholder="what you need help with"
                    style={{ borderBottom: "none" }}
                  />
                  <div className={styles.search_icon}>
                    <FontAwesomeIcon
                      icon={faMagnifyingGlass}
                      style={{ fontSize: 15, color: "#ffffff" }}
                    />
                  </div>
                </div>
              </div>
              <div className={styles.search_learn_more}>
                <p>Learn more about being a mentor and mentee</p>
              </div>
            </div>
          </div>
          <div className={styles.members_box}>
            <h1 className="sub_title" style={{ marginLeft: "50px" }}>
              Welcome to our <b>Recent Members</b>
            </h1>
            <div style={{ padding: `0 ${chevronWidth}px`, marginLeft: "10px" }}>
              <ItemsCarousel
                requestToChangeActive={setActiveItemIndex}
                activeItemIndex={activeItemIndex}
                numberOfCards={6}
                gutter={20}
                leftChevron={<button>{"<"}</button>}
                rightChevron={<button>{">"}</button>}
                outsideChevron
                chevronWidth={chevronWidth}
              >
                <MemberCard width={200} height={200} />
                <MemberCard width={200} height={200} />
                <MemberCard width={200} height={200} />
                <MemberCard width={200} height={200} />
                <MemberCard width={200} height={200} />
                <MemberCard width={200} height={200} />
                <MemberCard width={200} height={200} />
                <MemberCard width={200} height={200} />
              </ItemsCarousel>
            </div>
          </div>
          <div className={styles.opportunities_box}>
            <h1 className="sub_title">
              Recent <b>Mentoring Opportunities</b>
            </h1>
            <div className={styles.opportunities}>
              <OpportunityCard />
              <OpportunityCard />
            </div>
            <h1 className="read_more">Mentoring requests</h1>
          </div>
          <div className={styles.invite_box}>
            <Image
              style={{ width: "250px" }}
              src="/invite.jpg"
              alt="invite friends"
              className={styles.invite_pic}
              width={600}
              height={400}
            />
            <div className={styles.email_Box}>
              <div>
                <h1 style={{ fontSize: "34px", fontWeight: "500" }}>
                  Know someone who could be a good mentor ?
                </h1>
                <p className="text" style={{ marginTop: "10px" }}>
                  Invite them to join our community
                </p>
                <div className={styles.email_input}>
                  <p style={{ padding: "10px 60px", color: "#c3c3c3" }}>
                    Email address
                  </p>
                  <button className="button secondary_button">Send</button>
                </div>
              </div>
            </div>
          </div>
          <div className={styles.requests_box}>
            <h1 className="sub_title">
              Recent <b>Mentoring Requests</b>
            </h1>
            <RequestCard />
            <RequestCard />
            <h1 className="read_more">More Requests</h1>
          </div>
          <div className={classNames(styles.faq_box, "horizontal")}>
            <div>
              <h1 className="sub_title">
                Having <b>any questions ?</b>
              </h1>
              <p className="title">Take a look at our FAQ</p>
            </div>
            <div className="column">
              <div
                className={styles.question}
                onClick={() =>
                  setShow(show == "questionOne" ? "" : "questionOne")
                }
              >
                <h1 className="title">
                  How much does it cost to book a mentor?
                </h1>
                {show == "questionOne" && (
                  <div>
                    <h1>
                      Absolutely nothing. isn’t that amazing? we are community
                      on a mission to democratise mentorship for all, at no cost
                    </h1>
                  </div>
                )}
              </div>
              <div
                className={styles.question}
                onClick={() =>
                  setShow(show == "questionTwo" ? "" : "questionTwo")
                }
              >
                <h1 className="title">
                  What is a no-show? What is a no show policy ?
                </h1>
                {show == "questionTwo" && (
                  <div>
                    <h1>
                      A no-show is defined as missing you scheduled appointment
                      without informing the other party, we take a serious
                      commitment towards abuse and behaviour that goes agenst
                      the trusr and safety of out community. This is why we
                      developed our no show policy .
                    </h1>
                  </div>
                )}
              </div>
              <div
                className={styles.question}
                onClick={() =>
                  setShow(show == "questionThree" ? "" : "questionThree")
                }
              >
                <h1 className="title">
                  How long is the review process for a mentor application ?
                </h1>
                {show == "questionThree" && (
                  <div>
                    <h1>
                      It depends on the mentor you requested to be mentored by,
                      but usually it doesn't take more than three days
                    </h1>
                  </div>
                )}
              </div>
              <div
                className={styles.question}
                onClick={() =>
                  setShow(show == "questionFour" ? "" : "questionFour")
                }
              >
                <h1 className="title">How do i change my email address?</h1>
                {show == "questionFour" && (
                  <div>
                    <h1>
                      By clicking on profile settings and editing your profile
                      information
                    </h1>
                  </div>
                )}
              </div>
              <div
                className={styles.question}
                onClick={() =>
                  setShow(show == "questionFive" ? "" : "questionFive")
                }
              >
                <h1 className="title">How can i become a VIP Mentor?</h1>
                {show == "questionFive" && (
                  <div>
                    <h1>
                      Vip Mentors are selected carefully by our committee based
                      on feedback given from previous Mentees and on our own
                      research and data
                    </h1>
                  </div>
                )}
              </div>
            </div>
          </div>
          <div className={styles.members_box}>
            <h1 className="sub_title" style={{ marginLeft: "50px" }}>
              Mentors in your location
            </h1>
            <div style={{ padding: `0 ${chevronWidth}px`, marginLeft: "10px" }}>
              <ItemsCarousel
                requestToChangeActive={setActiveItemIndex}
                activeItemIndex={activeItemIndex}
                numberOfCards={4}
                gutter={20}
                leftChevron={<button>{"<"}</button>}
                rightChevron={<button>{">"}</button>}
                outsideChevron
                chevronWidth={chevronWidth}
              >
                <MemberCard width={250} height={250} />
                <MemberCard width={250} height={250} />
                <MemberCard width={250} height={250} />
                <MemberCard width={250} height={250} />
                <MemberCard width={250} height={250} />
              </ItemsCarousel>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch("http://localhost:8000/api");
  const data = await response.json();

  return {
    props: {
      data: data,
      done: true,
    },
  };
}
